#!/usr/bin/env bash
# Create an app and an API key through the operator's admin API (quickstart
# steps 8-10).
#
# The API is not exposed through the gateway -- it is an admin surface -- so we
# reach it with a short-lived port-forward. Credentials are written to
# .local/app.env, which is gitignored. They are never echoed in full.
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

APP_NAME="${APP_NAME:-example-app}"
ENV_FILE="$LOCAL_DIR/app.env"

port_forward "$NAMESPACE" deployments/ditto-operator 8080
API="http://127.0.0.1:${PF_PORT}/namespace/${NAMESPACE}/bigPeer/${BIGPEER_NAME}"

# Reuse the app if it already exists so the target is idempotent.
log "creating app '$APP_NAME'"
create=$(curl -s -H 'Content-Type: application/json' -X POST "${API}/app" \
  -d "{\"name\":\"${APP_NAME}\"}" || true)

app_id=$(jq -r '.appId // .id // empty' <<<"$create" 2>/dev/null || true)

if [[ -z "$app_id" ]]; then
  log "create returned no appId; looking the app up instead"
  app_id=$(curl -s "${API}/app" 2>/dev/null \
    | jq -r --arg n "$APP_NAME" '.. | objects | select(.name==$n) | (.appId // .id) // empty' \
    | head -1 || true)
fi

[[ -n "$app_id" ]] || {
  warn "operator response was: $create"
  die "could not determine appId"
}
log "appId: $app_id"

# An API key can only be read at creation time, and the operator rejects a
# duplicate key name -- so re-running with a fixed name fails. If we already
# hold a key for this app, keep it; otherwise mint one under a unique name.
if [[ -f "$ENV_FILE" ]] && ! force; then
  existing_id=$(sed -n 's/^DITTO_APP_ID=//p' "$ENV_FILE" | head -1)
  existing_key=$(sed -n 's/^DITTO_API_KEY=//p' "$ENV_FILE" | head -1)
  if [[ "$existing_id" == "$app_id" && -n "$existing_key" ]]; then
    skip "API key for $APP_NAME (in $ENV_FILE)"
    log "appId ${app_id}, API key ${existing_key:0:6}... (truncated)"
    exit 0
  fi
fi

KEY_NAME="${KEY_NAME:-makefile-$(date +%Y%m%d%H%M%S)}"
log "generating API key '$KEY_NAME'"
key_json=$(curl -s -H 'Content-Type: application/json' \
  -X POST "${API}/app/${APP_NAME}/apiKey" \
  -d '{
        "name": "'"${KEY_NAME}"'",
        "expiresAt": "2100-04-13T12:00:00Z",
        "permissions": {
          "remoteQuery": true,
          "read":  { "everything": true, "queriesByCollection": {} },
          "write": { "everything": true, "queriesByCollection": {} }
        }
      }')

# The operator returns the key as a bare string, not JSON. Try JSON first in
# case that changes, then fall back to treating the body as the key itself.
api_key=$(jq -r '.apiKey // .key // .value // empty' <<<"$key_json" 2>/dev/null || true)
if [[ -z "$api_key" ]]; then
  candidate=$(tr -d '[:space:]' <<<"$key_json")
  # A bare token: no JSON punctuation, plausible length.
  if [[ "$candidate" =~ ^[A-Za-z0-9._-]{20,}$ ]]; then
    api_key="$candidate"
  fi
fi

[[ -n "$api_key" ]] || {
  # Safe to show: we only reach here when the body did NOT look like a bare
  # token, so it is an error payload rather than a credential.
  warn "apiKey endpoint returned an unrecognised ${#key_json}-byte response:"
  warn "  $(head -c 300 <<<"$key_json")"
  die "could not extract the API key"
}

umask 077
cat > "$ENV_FILE" <<EOF
# Generated by scripts/app.sh -- contains credentials, do not commit.
DITTO_APP_ID=${app_id}
DITTO_API_KEY=${api_key}
DITTO_PLAYGROUND_TOKEN=${SHARED_TOKEN}
DITTO_APP_NAME=${APP_NAME}
EOF

log "wrote $ENV_FILE (mode 600)"
log "appId ${app_id}, API key ${api_key:0:6}... (truncated)"
