#!/usr/bin/env bash
# Derive the Makefile's config from config.yaml, for use before the first
# `terraform apply` has written .env.
#
# Terraform writes the same three keys on apply, from the state it actually
# built. This is the bootstrap path so `make` is usable on a fresh checkout,
# before any cluster exists.
#
# Emits KEY=VALUE on stdout. Usage: scripts/config.sh [deployment-name]

set -euo pipefail

CONFIG="${CONFIG_PATH:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/config.yaml}"

# Deliberately NOT defaulted from $DEPLOYMENT: the Makefile exports its own
# placeholder default, which would make this select a deployment that does not
# exist. An empty selector means "the first one defined".
WANT="${1:-}"

[[ -f "$CONFIG" ]] || { echo "config.yaml not found at $CONFIG" >&2; exit 1; }

# YAML has no portable CLI parser, so try what is most likely to be present.
# Order: yq (purpose-built) -> python+PyYAML -> ruby (ships with macOS).
emit() {
  if command -v yq >/dev/null 2>&1; then
    yq -r --arg want "$WANT" '
      .deployments as $d
      | (if $want != "" then $want else ($d | keys | .[0]) end) as $name
      | $d[$name] as $dep
      | "DEPLOYMENT=\($name)",
        "CLUSTER=\($dep.cluster.name)",
        "REGION=\($dep.region)"
    ' "$CONFIG"
    return
  fi

  if python3 -c 'import yaml' >/dev/null 2>&1; then
    CONFIG="$CONFIG" WANT="$WANT" python3 - <<'PY'
import os, yaml
cfg = yaml.safe_load(open(os.environ["CONFIG"]))
deps = cfg["deployments"]
name = os.environ.get("WANT") or next(iter(deps))
d = deps[name]
print(f"DEPLOYMENT={name}")
print(f"CLUSTER={d['cluster']['name']}")
print(f"REGION={d['region']}")
PY
    return
  fi

  if command -v ruby >/dev/null 2>&1 && ruby -ryaml -e '' >/dev/null 2>&1; then
    CONFIG="$CONFIG" WANT="$WANT" ruby -ryaml -e '
      cfg  = YAML.load_file(ENV["CONFIG"])
      deps = cfg["deployments"]
      name = (ENV["WANT"].to_s.empty? ? deps.keys.first : ENV["WANT"])
      d    = deps.fetch(name) { abort "deployment #{name} not found in config.yaml" }
      puts "DEPLOYMENT=#{name}"
      puts "CLUSTER=#{d["cluster"]["name"]}"
      puts "REGION=#{d["region"]}"
    '
    return
  fi

  cat >&2 <<'MSG'
No YAML parser available. Install one of:
    brew install yq          (recommended)
    pip3 install pyyaml
...or run `terraform apply` first, which generates .env directly.
MSG
  exit 1
}

echo "# Generated by scripts/config.sh from config.yaml."
echo "# \`terraform apply\` overwrites this with the values it actually built."
emit
