name: Release

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # The base64 of the contents of your '.p12' key.
          MACOS_SIGN_P12: ${{ secrets.MACOS_SIGN_P12 }}
          # The password to open the '.p12' key.
          MACOS_SIGN_PASSWORD: ${{ secrets.MACOS_SIGN_PASSWORD }}
          # The base64 of the contents of your '.p8' key.
          MACOS_NOTARY_KEY: ${{ secrets.MACOS_NOTARY_KEY }}
          # The ID of the '.p8' key.
          # You can find it in the filename, as well as the Apple Developer Portal
          # website.
          MACOS_NOTARY_KEY_ID: ${{ secrets.MACOS_NOTARY_KEY_ID }}
          # The issuer UUID.
          # You can find it in the Apple Developer Portal website.
          MACOS_NOTARY_ISSUER_ID: ${{ secrets.MACOS_NOTARY_ISSUER_ID }}
