# Terraform is the source of truth for what actually got built, so it writes the
# handful of values the Makefile needs to target the right cluster. Everything
# else the Makefile can discover from the cluster itself.
#
# This file is regenerated on every apply, so it holds nothing a human would
# want to edit. User-owned settings (AWS profile, Big Peer name, EXTERNAL, ...)
# belong in .env.local, which Terraform never touches. See .env.example.
#
# The Makefile falls back to scripts/config.sh, which parses config.yaml
# directly, so `make` is usable before the first apply.

locals {
  # With a single deployment the choice is unambiguous. With several, the caller
  # picks one with -var primary_deployment=<name>.
  primary_deployment = (
    var.primary_deployment != null
    ? var.primary_deployment
    : (length(local.deployments) == 1 ? one(keys(local.deployments)) : null)
  )

  primary = local.primary_deployment != null ? module.deployment[local.primary_deployment] : null
}

resource "local_file" "env" {
  count = local.primary_deployment != null ? 1 : 0

  filename        = "${path.module}/.env"
  file_permission = "0644"

  content = <<-EOT
    # Generated by terraform (env.tf) -- do not edit; re-run `terraform apply`.
    # Put your own overrides in .env.local instead. See .env.example.
    DEPLOYMENT=${local.primary_deployment}
    CLUSTER=${local.primary.cluster_name}
    REGION=${local.primary.region}
  EOT

  lifecycle {
    precondition {
      condition     = local.primary_deployment != null
      error_message = "Multiple deployments are defined; choose one with -var primary_deployment=<name>."
    }
  }
}

output "env_file" {
  description = "Path to the generated .env consumed by the Makefile."
  value       = local.primary_deployment != null ? local_file.env[0].filename : null
}
